# Showed as the Message to Confirm the Command
ConfirmMessage: '&aClick to Confirm'
# Showed as the Hover Message to Confirm the Command
ConfirmMessageHoverText: '&2Click to confirm the Command'
# Showed as the Message to Cancel the Command
CancelMessage: '&4Click to cancel'
# Showed as the Hover Message to Cancel the Command
CancelMessageHoverText: '&cClick to cancel the Command'

# INFOS
# You can use Farbcodes
# Please use the Standard Pattern of the Command List


# Pattern:
# Commandlist:
#   <command>: true
# Commandssettings:
#   <command>:
#     message: '<message>'
#

# Please write everything in lower case

# Here you can write in all commands where the plugin should do something
Commandlist:
  - clearinventory
  - essentials

# Here you can change the settings of specific commands
Commandsettings:
  clearinventory:
  
#   The Message that would be send before the Confirm and Cancel Message
    message: '&cDo you really want to delete your entire inventory?'
    
# Actiontype is currently in development
#   actiontype: Kick

# Actionmessage is currently in development
#   actionmessage: Kick
  essentials:
    message: '&cYou don''t do that!'

# Actiontype is currently in development
#   actiontype: Kick

# Actionmessage is currently in development
#   actionmessage: Kick